# Generated by Django 5.2 on 2025-04-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='saving',
            table='saving',
        ),
    ]
