# Generated by Django 5.2 on 2025-04-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_saving_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='collected',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
