# Generated by Django 5.2 on 2025-04-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_saving_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
