# Generated by Django 5.2 on 2025-04-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_saving_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savinglogs',
            name='nominal',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
