# Generated by Django 5.2 on 2025-04-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_savinglogs_nominal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savinglogs',
            name='description',
            field=models.TextField(blank=True, max_length=270),
        ),
    ]
