# Generated by Django 5.2 on 2025-04-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_savinglogs_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savinglogs',
            name='user',
        ),
    ]
